open("Q:/Abteilungsprojekte/eco/ResGroups/Narwani/Eawag/GROUP/Joey Bernhardt/imaging/190520_132102_Rstar_chla_phosphate_plate10/190520_132102_Plate 1/G6_01_1_1_Chlorophyll A_001.tif");
run("Duplicate...", " ");
setAutoThreshold("Default dark no-reset");
//run("Threshold...");
setOption("BlackBackground", true);
run("Convert to Mask");
run("Watershed");
run("Set Measurements...", "area mean min display redirect=[G6_01_1_1_Chlorophyll A_001.tif] decimal=1");
run("Analyze Particles...", "size=10-75 display exclude clear");
saveAs("Results", "Q:/Abteilungsprojekte/eco/ResGroups/Narwani/Eawag/GROUP/Joey Bernhardt/Fluo_per_cell/Results/ChlA_10_G6_1.csv");run("Close");
close();
selectWindow("G6_01_1_1_Chlorophyll A_001.tif");
close();
